# Autogenerated by devscripts/update-version.py

__version__ = '2023.05.25.023208'

RELEASE_GIT_HEAD = '309726d6a3f1eaf605384f4f2f0ea06d1848b176'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
