# Autogenerated by devscripts/update-version.py

__version__ = '2023.03.23.040309'

RELEASE_GIT_HEAD = '98242bd552ba91d58ef5665c824fa377d5c82e00'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
